### ISSUE TITLE
Master does not build under Eclipse

### ISSUE THREAD

**Issue by edwardalee** [lf-lang/lingua-franca#1258]
I get many errors in master trying to build under Eclipse:
```
Description	Resource	Path	Location	Type
The project was not built since its build path is incomplete. Cannot find the class file for org.eclipse.lsp4j.services.LanguageClient. Fix the build path then try building this project	org.lflang.diagram		Unknown	Java Problem
DiagnosticSeverity cannot be resolved to a type	PythonValidator.java	/org.lflang/src/org/lflang/generator/python	line 98	Java Problem
DiagnosticSeverity cannot be resolved to a type	PythonValidator.java	/org.lflang/src/org/lflang/generator/python	line 322	Java Problem
DiagnosticSeverity cannot be resolved to a variable	PythonValidator.java	/org.lflang/src/org/lflang/generator/python	line 103	Java Problem
DiagnosticSeverity cannot be resolved to a variable	PythonValidator.java	/org.lflang/src/org/lflang/generator/python	line 105	Java Problem
DiagnosticSeverity cannot be resolved to a variable	PythonValidator.java	/org.lflang/src/org/lflang/generator/python	line 108	Java Problem
DiagnosticSeverity cannot be resolved to a variable	PythonValidator.java	/org.lflang/src/org/lflang/generator/python	line 111	Java Problem
DiagnosticSeverity cannot be resolved to a variable	PythonValidator.java	/org.lflang/src/org/lflang/generator/python	line 193	Java Problem
DiagnosticSeverity cannot be resolved to a variable	PythonValidator.java	/org.lflang/src/org/lflang/generator/python	line 199	Java Problem
DiagnosticSeverity cannot be resolved to a variable	PythonValidator.java	/org.lflang/src/org/lflang/generator/python	line 224	Java Problem
DiagnosticSeverity cannot be resolved to a variable	PythonValidator.java	/org.lflang/src/org/lflang/generator/python	line 332	Java Problem
The import org.eclipse.lsp4j cannot be resolved	PythonValidator.java	/org.lflang/src/org/lflang/generator/python	line 12	Java Problem
The method getSeverity() from the type PythonValidator.PylintMessage refers to the missing type DiagnosticSeverity	PythonValidator.java	/org.lflang/src/org/lflang/generator/python	line 283	Java Problem
Diagnostic cannot be resolved to a type	MockLanguageClient.java	/org.lflang.tests/src/org/lflang/tests/lsp	line 23	Java Problem
Diagnostic cannot be resolved to a type	MockLanguageClient.java	/org.lflang.tests/src/org/lflang/tests/lsp	line 32	Java Problem
Diagnostic cannot be resolved to a type	MockLanguageClient.java	/org.lflang.tests/src/org/lflang/tests/lsp	line 33	Java Problem
Diagnostic cannot be resolved to a type	MockLanguageClient.java	/org.lflang.tests/src/org/lflang/tests/lsp	line 60	Java Problem
Diagnostic cannot be resolved to a type	MockLanguageClient.java	/org.lflang.tests/src/org/lflang/tests/lsp	line 61	Java Problem
Diagnostic cannot be resolved to a type	MockLanguageClient.java	/org.lflang.tests/src/org/lflang/tests/lsp	line 66	Java Problem
DiagnosticSeverity cannot be resolved to a variable	MockLanguageClient.java	/org.lflang.tests/src/org/lflang/tests/lsp	line 35	Java Problem
DiagnosticSeverity cannot be resolved to a variable	MockLanguageClient.java	/org.lflang.tests/src/org/lflang/tests/lsp	line 35	Java Problem
LanguageClient cannot be resolved to a type	MockLanguageClient.java	/org.lflang.tests/src/org/lflang/tests/lsp	line 21	Java Problem
MessageActionItem cannot be resolved to a type	MockLanguageClient.java	/org.lflang.tests/src/org/lflang/tests/lsp	line 49	Java Problem
MessageParams cannot be resolved to a type	MockLanguageClient.java	/org.lflang.tests/src/org/lflang/tests/lsp	line 44	Java Problem
MessageParams cannot be resolved to a type	MockLanguageClient.java	/org.lflang.tests/src/org/lflang/tests/lsp	line 55	Java Problem
PublishDiagnosticsParams cannot be resolved to a type	MockLanguageClient.java	/org.lflang.tests/src/org/lflang/tests/lsp	line 31	Java Problem
ShowMessageRequestParams cannot be resolved to a type	MockLanguageClient.java	/org.lflang.tests/src/org/lflang/tests/lsp	line 49	Java Problem
The import org.eclipse.lsp4j cannot be resolved	MockLanguageClient.java	/org.lflang.tests/src/org/lflang/tests/lsp	line 8	Java Problem
The import org.eclipse.lsp4j cannot be resolved	MockLanguageClient.java	/org.lflang.tests/src/org/lflang/tests/lsp	line 9	Java Problem
The import org.eclipse.lsp4j cannot be resolved	MockLanguageClient.java	/org.lflang.tests/src/org/lflang/tests/lsp	line 10	Java Problem
The import org.eclipse.lsp4j cannot be resolved	MockLanguageClient.java	/org.lflang.tests/src/org/lflang/tests/lsp	line 11	Java Problem
The import org.eclipse.lsp4j cannot be resolved	MockLanguageClient.java	/org.lflang.tests/src/org/lflang/tests/lsp	line 12	Java Problem
The import org.eclipse.lsp4j cannot be resolved	MockLanguageClient.java	/org.lflang.tests/src/org/lflang/tests/lsp	line 13	Java Problem
The import org.eclipse.lsp4j cannot be resolved	MockLanguageClient.java	/org.lflang.tests/src/org/lflang/tests/lsp	line 14	Java Problem
The method telemetryEvent(Object) of type MockLanguageClient must override or implement a supertype method	MockLanguageClient.java	/org.lflang.tests/src/org/lflang/tests/lsp	line 26	Java Problem
Unsatisfied version constraint: 'org.eclipse.core.runtime: 3.25.0'	MANIFEST.MF	/org.lflang/META-INF	line 24	Plug-in Problem
Unsatisfied version constraint: 'org.eclipse.elk.alg.layered: 0.8.1'	MANIFEST.MF	/org.lflang.diagram/META-INF	line 16	Plug-in Problem
Unsatisfied version constraint: 'org.eclipse.elk.core: 0.8.1'	MANIFEST.MF	/org.lflang.diagram/META-INF	line 15	Plug-in Problem
Unsatisfied version constraint: 'org.eclipse.lsp4j: 0.14.0'	MANIFEST.MF	/org.lflang.diagram/META-INF	line 21	Plug-in Problem
Unsatisfied version constraint: 'org.eclipse.lsp4j: 0.14.0'	MANIFEST.MF	/org.lflang.tests/META-INF	line 17	Plug-in Problem
Unsatisfied version constraint: 'org.eclipse.lsp4j: 0.14.0'	MANIFEST.MF	/org.lflang/META-INF	line 20	Plug-in Problem
Unsatisfied version constraint: 'org.eclipse.lsp4j.jsonrpc: 0.14.0'	MANIFEST.MF	/org.lflang.diagram/META-INF	line 22	Plug-in Problem
Unsatisfied version constraint: 'org.eclipse.xtext.ide: 2.27.0'	MANIFEST.MF	/org.lflang.diagram/META-INF	line 20	Plug-in Problem
Unsatisfied version constraint: 'org.eclipse.xtext.xbase.lib: 2.27.0'	MANIFEST.MF	/org.lflang.tests/META-INF	line 13	Plug-in Problem
Unsatisfied version constraint: 'org.eclipse.xtext.xbase.lib: 2.27.0'	MANIFEST.MF	/org.lflang.ui/META-INF	line 19	Plug-in Problem
Unsatisfied version constraint: 'org.eclipse.xtext.xbase.lib: 2.27.0'	MANIFEST.MF	/org.lflang/META-INF	line 13	Plug-in Problem
Diagnostic cannot be resolved to a type	LspTests.java	/org.lflang.tests/src/org/lflang/tests/lsp	line 40	Java Problem
Diagnostic cannot be resolved to a type	LspTests.java	/org.lflang.tests/src/org/lflang/tests/lsp	line 41	Java Problem
Diagnostic cannot be resolved to a type	LspTests.java	/org.lflang.tests/src/org/lflang/tests/lsp	line 92	Java Problem
Diagnostic cannot be resolved to a type	LspTests.java	/org.lflang.tests/src/org/lflang/tests/lsp	line 126	Java Problem
Diagnostic cannot be resolved to a type	LspTests.java	/org.lflang.tests/src/org/lflang/tests/lsp	line 180	Java Problem
Diagnostic cannot be resolved to a type	LspTests.java	/org.lflang.tests/src/org/lflang/tests/lsp	line 191	Java Problem
The import org.eclipse.lsp4j cannot be resolved	LspTests.java	/org.lflang.tests/src/org/lflang/tests/lsp	line 13	Java Problem
The method checkDiagnostics(Target, Function<ErrorInserter.AlteredTest,Predicate<List<Diagnostic>>>, ErrorInserter, Random) from the type LspTests refers to the missing type Diagnostic	LspTests.java	/org.lflang.tests/src/org/lflang/tests/lsp	line 90	Java Problem
The method diagnosticsHaveKeyword(String) from the type LspTests refers to the missing type Diagnostic	LspTests.java	/org.lflang.tests/src/org/lflang/tests/lsp	line 40	Java Problem
The method diagnosticsHaveKeyword(String) from the type LspTests refers to the missing type Diagnostic	LspTests.java	/org.lflang.tests/src/org/lflang/tests/lsp	line 41	Java Problem
The method diagnosticsHaveKeyword(String) from the type LspTests refers to the missing type Diagnostic	LspTests.java	/org.lflang.tests/src/org/lflang/tests/lsp	line 42	Java Problem
The method diagnosticsIncludeText(String) from the type LspTests refers to the missing type Diagnostic	LspTests.java	/org.lflang.tests/src/org/lflang/tests/lsp	line 42	Java Problem
The method getReceivedDiagnostics() from the type MockLanguageClient refers to the missing type Diagnostic	LspTests.java	/org.lflang.tests/src/org/lflang/tests/lsp	line 137	Java Problem
The method getReceivedDiagnostics() from the type MockLanguageClient refers to the missing type Diagnostic	LspTests.java	/org.lflang.tests/src/org/lflang/tests/lsp	line 141	Java Problem
The method setClient(LanguageClient) from the type LanguageServerErrorReporter refers to the missing type LanguageClient	LspTests.java	/org.lflang.tests/src/org/lflang/tests/lsp	line 131	Java Problem
This lambda expression refers to the missing type Diagnostic	LspTests.java	/org.lflang.tests/src/org/lflang/tests/lsp	line 92	Java Problem
This lambda expression refers to the missing type Diagnostic	LspTests.java	/org.lflang.tests/src/org/lflang/tests/lsp	line 181	Java Problem
This lambda expression refers to the missing type Diagnostic	LspTests.java	/org.lflang.tests/src/org/lflang/tests/lsp	line 192	Java Problem
Diagnostic cannot be resolved to a type	LanguageServerErrorReporter.java	/org.lflang/src/org/lflang/generator	line 38	Java Problem
Diagnostic cannot be resolved to a type	LanguageServerErrorReporter.java	/org.lflang/src/org/lflang/generator	line 51	Java Problem
Diagnostic cannot be resolved to a type	LanguageServerErrorReporter.java	/org.lflang/src/org/lflang/generator	line 103	Java Problem
Diagnostic cannot be resolved to a type	LanguageServerErrorReporter.java	/org.lflang/src/org/lflang/generator	line 128	Java Problem
Diagnostic cannot be resolved to a type	LanguageServerErrorReporter.java	/org.lflang/src/org/lflang/generator	line 129	Java Problem
Diagnostic cannot be resolved to a type	LanguageServerErrorReporter.java	/org.lflang/src/org/lflang/generator	line 129	Java Problem
Diagnostic cannot be resolved to a type	LanguageServerErrorReporter.java	/org.lflang/src/org/lflang/generator	line 154	Java Problem
Diagnostic cannot be resolved to a type	LanguageServerErrorReporter.java	/org.lflang/src/org/lflang/generator	line 157	Java Problem
DiagnosticSeverity cannot be resolved to a type	LanguageServerErrorReporter.java	/org.lflang/src/org/lflang/generator	line 109	Java Problem
DiagnosticSeverity cannot be resolved to a type	LanguageServerErrorReporter.java	/org.lflang/src/org/lflang/generator	line 114	Java Problem
DiagnosticSeverity cannot be resolved to a type	LanguageServerErrorReporter.java	/org.lflang/src/org/lflang/generator	line 126	Java Problem
DiagnosticSeverity cannot be resolved to a variable	LanguageServerErrorReporter.java	/org.lflang/src/org/lflang/generator	line 58	Java Problem
DiagnosticSeverity cannot be resolved to a variable	LanguageServerErrorReporter.java	/org.lflang/src/org/lflang/generator	line 63	Java Problem
DiagnosticSeverity cannot be resolved to a variable	LanguageServerErrorReporter.java	/org.lflang/src/org/lflang/generator	line 68	Java Problem
DiagnosticSeverity cannot be resolved to a variable	LanguageServerErrorReporter.java	/org.lflang/src/org/lflang/generator	line 88	Java Problem
DiagnosticSeverity cannot be resolved to a variable	LanguageServerErrorReporter.java	/org.lflang/src/org/lflang/generator	line 93	Java Problem
DiagnosticSeverity cannot be resolved to a variable	LanguageServerErrorReporter.java	/org.lflang/src/org/lflang/generator	line 98	Java Problem
LanguageClient cannot be resolved to a type	LanguageServerErrorReporter.java	/org.lflang/src/org/lflang/generator	line 33	Java Problem
LanguageClient cannot be resolved to a type	LanguageServerErrorReporter.java	/org.lflang/src/org/lflang/generator	line 139	Java Problem
LanguageClient cannot be resolved to a type	LanguageServerErrorReporter.java	/org.lflang/src/org/lflang/generator	line 140	Java Problem
LanguageClient cannot be resolved to a type	LanguageServerErrorReporter.java	/org.lflang/src/org/lflang/generator	line 148	Java Problem
LanguageClient cannot be resolved to a type	LanguageServerErrorReporter.java	/org.lflang/src/org/lflang/generator	line 158	Java Problem
org.eclipse.lsp4j cannot be resolved to a type	LanguageServerErrorReporter.java	/org.lflang/src/org/lflang/generator	line 199	Java Problem
org.eclipse.lsp4j cannot be resolved to a type	LanguageServerErrorReporter.java	/org.lflang/src/org/lflang/generator	line 200	Java Problem
PublishDiagnosticsParams cannot be resolved to a type	LanguageServerErrorReporter.java	/org.lflang/src/org/lflang/generator	line 155	Java Problem
PublishDiagnosticsParams cannot be resolved to a type	LanguageServerErrorReporter.java	/org.lflang/src/org/lflang/generator	line 155	Java Problem
The import org.eclipse.lsp4j cannot be resolved	LanguageServerErrorReporter.java	/org.lflang/src/org/lflang/generator	line 12	Java Problem
The import org.eclipse.lsp4j cannot be resolved	LanguageServerErrorReporter.java	/org.lflang/src/org/lflang/generator	line 13	Java Problem
The import org.eclipse.lsp4j cannot be resolved	LanguageServerErrorReporter.java	/org.lflang/src/org/lflang/generator	line 14	Java Problem
The import org.eclipse.lsp4j cannot be resolved	LanguageServerErrorReporter.java	/org.lflang/src/org/lflang/generator	line 15	Java Problem
The import org.eclipse.lsp4j cannot be resolved	LanguageServerErrorReporter.java	/org.lflang/src/org/lflang/generator	line 17	Java Problem
The type org.eclipse.lsp4j.services.LanguageClient cannot be resolved. It is indirectly referenced from required .class files	LFLanguageServerExtension.java	/org.lflang.diagram/src/org/lflang/diagram/lsp	line 1	Java Problem
DiagnosticSeverity cannot be resolved to a type	HumanReadableReportingStrategy.java	/org.lflang/src/org/lflang/generator	line 111	Java Problem
The import org.eclipse.lsp4j cannot be resolved	HumanReadableReportingStrategy.java	/org.lflang/src/org/lflang/generator	line 10	Java Problem
The method severityOf(String) from the type DiagnosticReporting refers to the missing type DiagnosticSeverity	HumanReadableReportingStrategy.java	/org.lflang/src/org/lflang/generator	line 111	Java Problem
DiagnosticSeverity cannot be resolved to a type	ErrorReporter.java	/org.lflang/src/org/lflang	line 113	Java Problem
DiagnosticSeverity cannot be resolved to a type	ErrorReporter.java	/org.lflang/src/org/lflang	line 136	Java Problem
DiagnosticSeverity cannot be resolved to a type	ErrorReporter.java	/org.lflang/src/org/lflang	line 163	Java Problem
Error cannot be resolved to a variable	ErrorReporter.java	/org.lflang/src/org/lflang	line 115	Java Problem
Error cannot be resolved to a variable	ErrorReporter.java	/org.lflang/src/org/lflang	line 138	Java Problem
Hint cannot be resolved to a variable	ErrorReporter.java	/org.lflang/src/org/lflang	line 118	Java Problem
Hint cannot be resolved to a variable	ErrorReporter.java	/org.lflang/src/org/lflang	line 141	Java Problem
Information cannot be resolved to a variable	ErrorReporter.java	/org.lflang/src/org/lflang	line 119	Java Problem
Information cannot be resolved to a variable	ErrorReporter.java	/org.lflang/src/org/lflang	line 142	Java Problem
The import org.eclipse.lsp4j cannot be resolved	ErrorReporter.java	/org.lflang/src/org/lflang	line 6	Java Problem
Warning cannot be resolved to a variable	ErrorReporter.java	/org.lflang/src/org/lflang	line 117	Java Problem
Warning cannot be resolved to a variable	ErrorReporter.java	/org.lflang/src/org/lflang	line 140	Java Problem
DiagnosticSeverity cannot be resolved to a type	DiagnosticReporting.java	/org.lflang/src/org/lflang/generator	line 53	Java Problem
DiagnosticSeverity cannot be resolved to a variable	DiagnosticReporting.java	/org.lflang/src/org/lflang/generator	line 55	Java Problem
DiagnosticSeverity cannot be resolved to a variable	DiagnosticReporting.java	/org.lflang/src/org/lflang/generator	line 56	Java Problem
DiagnosticSeverity cannot be resolved to a variable	DiagnosticReporting.java	/org.lflang/src/org/lflang/generator	line 57	Java Problem
DiagnosticSeverity cannot be resolved to a variable	DiagnosticReporting.java	/org.lflang/src/org/lflang/generator	line 58	Java Problem
The import org.eclipse.lsp4j cannot be resolved	DiagnosticReporting.java	/org.lflang/src/org/lflang/generator	line 6	Java Problem
Referenced class 'org.eclipse.core.resources.IFile' in attribute 'type' is not on the plug-in classpath	plugin.xml	/org.lflang.product	line 63	Plug-in Problem
Referenced class 'org.eclipse.core.resources.IFolder' in attribute 'type' is not on the plug-in classpath	plugin.xml	/org.lflang.product	line 66	Plug-in Problem
Referenced class 'org.eclipse.core.resources.IProject' in attribute 'type' is not on the plug-in classpath	plugin.xml	/org.lflang.product	line 69	Plug-in Problem
Referenced identifier 'org.lflang.lf.compile.toolbar' in attribute 'commandId' cannot be found	plugin.xml	/org.lflang.ui	line 501	Plug-in Problem
Referenced identifier 'org.lflang.lf.compile.toolbar' in attribute 'commandId' cannot be found	plugin.xml	/org.lflang.ui	line 654	Plug-in Problem
Referenced identifier 'org.lflang.lf.compile' in attribute 'commandId' cannot be found	plugin.xml	/org.lflang.ui	line 497	Plug-in Problem
Referenced identifier 'org.lflang.lf.compile' in attribute 'commandId' cannot be found	plugin.xml	/org.lflang.ui	line 514	Plug-in Problem
Referenced identifier 'org.lflang.lf.compile' in attribute 'commandId' cannot be found	plugin.xml	/org.lflang.ui	line 531	Plug-in Problem
Referenced identifier 'org.lflang.lf.compile' in attribute 'commandId' cannot be found	plugin.xml	/org.lflang.ui	line 562	Plug-in Problem
Referenced identifier 'org.lflang.lf.compile' in attribute 'commandId' cannot be found	plugin.xml	/org.lflang.ui	line 593	Plug-in Problem
Referenced identifier 'org.lflang.lf.compile' in attribute 'commandId' cannot be found	plugin.xml	/org.lflang.ui	line 622	Plug-in Problem
The serializable class UnsupportedGeneratorFeatureException does not declare a static final serialVersionUID field of type long	UnsupportedGeneratorFeatureException.java	/org.lflang/src/org/lflang/generator	line 33	Java Problem
Type safety: Unchecked cast from TriggerInstance.BuiltinTriggerVariable to T	TriggerInstance.java	/org.lflang/src/org/lflang/generator	line 67	Java Problem
The import java.util.Optional is never used	TestRegistry.java	/org.lflang.tests/src/org/lflang/tests	line 20	Java Problem
The import org.eclipse.xtext.xbase.lib.IteratorExtensions.exists is never used	TestRegistry.java	/org.lflang.tests/src/org/lflang/tests	line 5	Java Problem
The import org.eclipse.xtext.xbase.lib.IteratorExtensions.filter is never used	TestRegistry.java	/org.lflang.tests/src/org/lflang/tests	line 6	Java Problem
The import org.lflang.lf.TargetDecl is never used	TestRegistry.java	/org.lflang.tests/src/org/lflang/tests	line 36	Java Problem
The import java.util.ArrayList is never used	TestBase.java	/org.lflang.tests/src/org/lflang/tests	line 21	Java Problem
The import java.util.HashMap is never used	TestBase.java	/org.lflang.tests/src/org/lflang/tests	line 18	Java Problem
The import java.util.Map is never used	TestBase.java	/org.lflang.tests/src/org/lflang/tests	line 19	Java Problem
The import java.util.Locale is never used	RustTargetConfig.java	/org.lflang/src/org/lflang/generator/rust	line 32	Java Problem
Unsupported @SuppressWarnings("FieldCanBeLocal")	PythonValidator.java	/org.lflang/src/org/lflang/generator/python	line 60	Java Problem
The import org.lflang.lf.TriggerRef is never used	PythonModeGenerator.java	/org.lflang/src/org/lflang/generator/python	line 13	Java Problem
The value of the field NamedInstance<T>._fullName is not used	NamedInstance.java	/org.lflang/src/org/lflang/generator	line 330	Java Problem
Bundle 'org.jetbrains.kotlin.bundled-compiler' cannot be resolved	MANIFEST.MF	/org.lflang/META-INF	line 19	Plug-in Problem
The value of the local variable testCase is not used	LinguaFrancaValidationTest.java	/org.lflang.tests/src/org/lflang/tests/compiler	line 1955	Java Problem
The value of the local variable testCase is not used	LinguaFrancaValidationTest.java	/org.lflang.tests/src/org/lflang/tests/compiler	line 1977	Java Problem
The value of the local variable testCase is not used	LinguaFrancaValidationTest.java	/org.lflang.tests/src/org/lflang/tests/compiler	line 2198	Java Problem
The import org.lflang.lf.LfPackage is never used	LinguaFrancaParsingTest.java	/org.lflang.tests/src/org/lflang/tests/compiler	line 34	Java Problem
Discouraged access: The method 'KlighdCanvas.getCamera()' is not API (restriction on required library '/Users/eal/.p2/pool/plugins/de.cau.cs.kieler.klighd.piccolo_2.1.0.v20210615.jar')	LinguaFrancaDiagramUpdateController.java	/org.lflang.ui/src/org/lflang/ui/diagram	line 94	Java Problem
Discouraged access: The type 'KlighdCanvas' is not API (restriction on required library '/Users/eal/.p2/pool/plugins/de.cau.cs.kieler.klighd.piccolo_2.1.0.v20210615.jar')	LinguaFrancaDiagramUpdateController.java	/org.lflang.ui/src/org/lflang/ui/diagram	line 38	Java Problem
Discouraged access: The type 'KlighdCanvas' is not API (restriction on required library '/Users/eal/.p2/pool/plugins/de.cau.cs.kieler.klighd.piccolo_2.1.0.v20210615.jar')	LinguaFrancaDiagramUpdateController.java	/org.lflang.ui/src/org/lflang/ui/diagram	line 92	Java Problem
Discouraged access: The type 'KlighdCanvas' is not API (restriction on required library '/Users/eal/.p2/pool/plugins/de.cau.cs.kieler.klighd.piccolo_2.1.0.v20210615.jar')	LinguaFrancaDiagramUpdateController.java	/org.lflang.ui/src/org/lflang/ui/diagram	line 93	Java Problem
Discouraged access: The type 'KlighdInputManager.KlighdInputEvent' is not API (restriction on required library '/Users/eal/.p2/pool/plugins/de.cau.cs.kieler.klighd.piccolo_2.1.0.v20210615.jar')	LinguaFrancaDiagramUpdateController.java	/org.lflang.ui/src/org/lflang/ui/diagram	line 39	Java Problem
Discouraged access: The type 'KlighdInputManager.KlighdInputEvent' is not API (restriction on required library '/Users/eal/.p2/pool/plugins/de.cau.cs.kieler.klighd.piccolo_2.1.0.v20210615.jar')	LinguaFrancaDiagramUpdateController.java	/org.lflang.ui/src/org/lflang/ui/diagram	line 122	Java Problem
Discouraged access: The type 'KlighdInputManager.KlighdInputEvent' is not API (restriction on required library '/Users/eal/.p2/pool/plugins/de.cau.cs.kieler.klighd.piccolo_2.1.0.v20210615.jar')	LinguaFrancaDiagramUpdateController.java	/org.lflang.ui/src/org/lflang/ui/diagram	line 124	Java Problem
Discouraged access: The type 'KlighdMainCamera' is not API (restriction on required library '/Users/eal/.p2/pool/plugins/de.cau.cs.kieler.klighd.piccolo_2.1.0.v20210615.jar')	LinguaFrancaDiagramUpdateController.java	/org.lflang.ui/src/org/lflang/ui/diagram	line 40	Java Problem
Discouraged access: The type 'KlighdMainCamera' is not API (restriction on required library '/Users/eal/.p2/pool/plugins/de.cau.cs.kieler.klighd.piccolo_2.1.0.v20210615.jar')	LinguaFrancaDiagramUpdateController.java	/org.lflang.ui/src/org/lflang/ui/diagram	line 63	Java Problem
The import org.eclipse.xtext.EOF is never used	LinguaFrancaDependencyAnalysisTest.java	/org.lflang.tests/src/org/lflang/tests/compiler	line 33	Java Problem
The import java.util.HashMap is never used	LFValidator.java	/org.lflang/src/org/lflang/validation	line 40	Java Problem
The import java.util.Map is never used	LFValidator.java	/org.lflang/src/org/lflang/validation	line 45	Java Problem
The import org.lflang.lf.AttrParm is never used	LFValidator.java	/org.lflang/src/org/lflang/validation	line 72	Java Problem
The import org.lflang.validation.AttributeSpec.AttrParamSpec is never used	LFValidator.java	/org.lflang/src/org/lflang/validation	line 117	Java Problem
The import org.lflang.validation.AttributeSpec.AttrParamType is never used	LFValidator.java	/org.lflang/src/org/lflang/validation	line 118	Java Problem
Unlikely argument type Instantiation for indexOf(Object) on a List<StateVar>	LFValidator.java	/org.lflang/src/org/lflang/validation	line 1394	Java Problem
The import java.util.LinkedList is never used	LFUiModuleImpl.java	/org.lflang.ui/src/org/lflang/ui	line 6	Java Problem
Unnecessary @SuppressWarnings("restriction")	LFUiModule.java	/org.lflang.ui/src/org/lflang/ui	line 38	Java Problem
The value of the local variable model is not used	LFSemanticHighlightingCalculator.java	/org.lflang.ui/src/org/lflang/ui/highlighting	line 58	Java Problem
The enum constant NULL needs a corresponding case label in this enum switch on LFScopeProviderImpl.RefType	LFScopeProviderImpl.java	/org.lflang/src/org/lflang/scoping	line 203	Java Problem
Discouraged access: The field 'ResourceMessages.FileResource_errorMessage' is not API (restriction on required library '/Users/eal/.p2/pool/plugins/org.eclipse.ui.ide_3.18.500.v20220215-1304.jar')	LFFileWizard.java	/org.lflang.ui/src/org/lflang/ui/wizard	line 71	Java Problem
Discouraged access: The method 'DialogUtil.openError(Shell, String, String, PartInitException)' is not API (restriction on required library '/Users/eal/.p2/pool/plugins/org.eclipse.ui.ide_3.18.500.v20220215-1304.jar')	LFFileWizard.java	/org.lflang.ui/src/org/lflang/ui/wizard	line 71	Java Problem
Discouraged access: The type 'DialogUtil' is not API (restriction on required library '/Users/eal/.p2/pool/plugins/org.eclipse.ui.ide_3.18.500.v20220215-1304.jar')	LFFileWizard.java	/org.lflang.ui/src/org/lflang/ui/wizard	line 15	Java Problem
Discouraged access: The type 'DialogUtil' is not API (restriction on required library '/Users/eal/.p2/pool/plugins/org.eclipse.ui.ide_3.18.500.v20220215-1304.jar')	LFFileWizard.java	/org.lflang.ui/src/org/lflang/ui/wizard	line 71	Java Problem
Discouraged access: The type 'ResourceMessages' is not API (restriction on required library '/Users/eal/.p2/pool/plugins/org.eclipse.ui.ide_3.18.500.v20220215-1304.jar')	LFFileWizard.java	/org.lflang.ui/src/org/lflang/ui/wizard	line 16	Java Problem
Discouraged access: The type 'ResourceMessages' is not API (restriction on required library '/Users/eal/.p2/pool/plugins/org.eclipse.ui.ide_3.18.500.v20220215-1304.jar')	LFFileWizard.java	/org.lflang.ui/src/org/lflang/ui/wizard	line 71	Java Problem
The import org.lflang.lf.Reactor is never used	IteratorUtil.java	/org.lflang/src/org/lflang/util	line 7	Java Problem
The serializable class InvalidSourceException does not declare a static final serialVersionUID field of type long	InvalidSourceException.java	/org.lflang/src/org/lflang/generator	line 37	Java Problem
The serializable class InvalidLfSourceException does not declare a static final serialVersionUID field of type long	InvalidLfSourceException.java	/org.lflang/src/org/lflang/generator	line 36	Java Problem
The import org.lflang.Target is never used	GeneratorUtils.java	/org.lflang/src/org/lflang/generator	line 24	Java Problem
Type safety: Unchecked cast from EObject to T	GeneratorUtils.java	/org.lflang/src/org/lflang/generator	line 186	Java Problem
The import java.util.List is never used	GeneratorResult.java	/org.lflang/src/org/lflang/generator	line 5	Java Problem
The serializable class GenerationException does not declare a static final serialVersionUID field of type long	GenerationException.java	/org.lflang/src/org/lflang/generator	line 34	Java Problem
Unsupported @SuppressWarnings("ClassCanBeRecord")	ErrorInserter.java	/org.lflang.tests/src/org/lflang/tests/lsp	line 26	Java Problem
Discouraged access: The method 'IProjectConfig.getName()' is not API (restriction on required library '/Users/eal/.p2/pool/plugins/org.eclipse.xtext_2.26.0.v20220228-0751.jar')	EclipseBasedShouldGenerateLF.java	/org.lflang.ui/src/org/lflang/ui	line 55	Java Problem
Discouraged access: The method 'ProjectConfigAdapter.findInEmfObject(Notifier)' is not API (restriction on required library '/Users/eal/.p2/pool/plugins/org.eclipse.xtext_2.26.0.v20220228-0751.jar')	EclipseBasedShouldGenerateLF.java	/org.lflang.ui/src/org/lflang/ui	line 52	Java Problem
Discouraged access: The method 'ProjectConfigAdapter.getProjectConfig()' is not API (restriction on required library '/Users/eal/.p2/pool/plugins/org.eclipse.xtext_2.26.0.v20220228-0751.jar')	EclipseBasedShouldGenerateLF.java	/org.lflang.ui/src/org/lflang/ui	line 54	Java Problem
Discouraged access: The type 'IProjectConfig' is not API (restriction on required library '/Users/eal/.p2/pool/plugins/org.eclipse.xtext_2.26.0.v20220228-0751.jar')	EclipseBasedShouldGenerateLF.java	/org.lflang.ui/src/org/lflang/ui	line 23	Java Problem
Discouraged access: The type 'IProjectConfig' is not API (restriction on required library '/Users/eal/.p2/pool/plugins/org.eclipse.xtext_2.26.0.v20220228-0751.jar')	EclipseBasedShouldGenerateLF.java	/org.lflang.ui/src/org/lflang/ui	line 54	Java Problem
Discouraged access: The type 'ProjectConfigAdapter' is not API (restriction on required library '/Users/eal/.p2/pool/plugins/org.eclipse.xtext_2.26.0.v20220228-0751.jar')	EclipseBasedShouldGenerateLF.java	/org.lflang.ui/src/org/lflang/ui	line 24	Java Problem
Discouraged access: The type 'ProjectConfigAdapter' is not API (restriction on required library '/Users/eal/.p2/pool/plugins/org.eclipse.xtext_2.26.0.v20220228-0751.jar')	EclipseBasedShouldGenerateLF.java	/org.lflang.ui/src/org/lflang/ui	line 52	Java Problem
Discouraged access: The type 'ProjectConfigAdapter' is not API (restriction on required library '/Users/eal/.p2/pool/plugins/org.eclipse.xtext_2.26.0.v20220228-0751.jar')	EclipseBasedShouldGenerateLF.java	/org.lflang.ui/src/org/lflang/ui	line 52	Java Problem
The import org.lflang.ASTUtils is never used	DeadlineInstance.java	/org.lflang/src/org/lflang/generator	line 30	Java Problem
The import org.lflang.lf.Parameter is never used	DeadlineInstance.java	/org.lflang/src/org/lflang/generator	line 33	Java Problem
The import org.junit.jupiter.api.Assumptions is never used	CppTest.java	/org.lflang.tests/src/org/lflang/tests/runtime	line 29	Java Problem
The import org.lflang.tests.TestRegistry.TestCategory is never used	CppRos2Test.java	/org.lflang.tests/src/org/lflang/tests/runtime	line 11	Java Problem
The import org.lflang.ASTUtils is never used	CGeneratorExtension.java	/org.lflang/src/org/lflang/federated	line 31	Java Problem
The import org.lflang.generator.c.CGenerator is never used	CGeneratorExtension.java	/org.lflang/src/org/lflang/federated	line 34	Java Problem
The import org.lflang.lf.Parameter is never used	CGeneratorExtension.java	/org.lflang/src/org/lflang/federated	line 39	Java Problem
The import org.lflang.TargetConfig is never used	CGeneratorExtension.java	/org.lflang/src/org/lflang/federated	line 30	Java Problem
The import java.nio.file.Path is never used	CCoreFilesUtils.java	/org.lflang/src/org/lflang/generator/c	line 2	Java Problem
The import org.lflang.lf.Attribute is never used	ASTUtils.java	/org.lflang/src/org/lflang	line 65	Java Problem
Unlikely argument type for equals(): Instantiation seems to be unrelated to ReactorInstance	LFValidator.java	/org.lflang/src/org/lflang/validation	line 214	Java Problem
Unlikely argument type for equals(): Instantiation seems to be unrelated to ReactorInstance	LFValidator.java	/org.lflang/src/org/lflang/validation	line 222	Java Problem
```

**Comment by petervdonovan** [comment]
Could this be related to #1234, which was merged two days ago? Maybe we simply forgot to update the Oomph setup when we were bumping versions... I will look into it.

**Comment by lhstrh** [comment]
@edwardalee: Note that the fix I pushed requires running `Help->Perform Setup Tasks...`

**Comment by edwardalee** [comment]
Sorry, the comment was prematurely posted, before I finished it. More info above.  What version of Eclipse are you running?

**Comment by lhstrh** [comment]
I'm using `2022-06`, which I suspect might be required to build...

**Comment by lhstrh** [comment]
I have also noticed that a restart is sometimes required when running setup tasks. In my experience getting stuff to build in Eclipse is always jenky. The only way to reliably get a working setup is do a clean Oomph install.

**Comment by edwardalee** [comment]
Updating Eclipse and fresh Oomph install still does not work. org.eclipse.lsp4j is not found.

**Comment by lhstrh** [comment]
Not sure what to do with this; I got it to work on my machine without problems. I didn't even do an Oomph setup -- I just ran the setup tasks. Maybe we should try to debug this together?

**Comment by edwardalee** [comment]
I suspect you already had org.eclipse.lsp4j installed manually as a jar file.

**Comment by lhstrh** [comment]
It’s specified as a dependency in the MANIFEST.MF so it should be pulled
in. I never manually added any jar to the build path. We had this
dependency already; it’s just the version that got bumped…

**Comment by lhstrh** [comment]
This was resolved. It turned out that there was latent state from earlier Gradle builds that caused problems. Invoking `./gradlew clean` fixed the problem.
