### ISSUE TITLE
Stop special casing `{= 0 =}`

### ISSUE THREAD

**Issue by oowekyala** [lf-lang/lingua-franca#657]
It's very useful to allow specifying a zero duration as just "0":
```
a: time(0)
```

But in #544 I found out we go out of our way to interpret `{= 0 =}` in the same way. I think that's not useful (why would you write `{=0=}` if you can write `0`), and also introduces a dangerous precedent for trying to interpret the contents of `{=...=}`. Using `0 ms` or `0` is the *LF* syntax to express time, and `{= 0 =}` is the target language syntax, which we're supposed not to make any assumptions about. Also our implementation could be simpler if we didn't support it.

I think we should just remove support for that.

**Comment by cmnrd** [comment]
I learned that the interpretation of the contents within `{=...=}` also happens in other places. For instance, the C code generator interprets `{=foo*=}` as a token type.

**Comment by oowekyala** [comment]
Interesting... Maybe C should support a type syntax like `token<foo>`? Since C doesn't support generics, this doesn't conflict with C syntax itself

**Comment by Soroosh129** [comment]
> I learned that the interpretation of the contents within `{=...=}` also happens in other places. For instance, the C code generator interprets `{=foo*=}` as a token type.

This sounds like a bug. I think the code generator should not try to string match whatever is inside `{=...=}` to look for a `*`.

**Comment by lhstrh** [comment]
> > I learned that the interpretation of the contents within `{=...=}` also happens in other places. For instance, the C code generator interprets `{=foo*=}` as a token type.
> 
> This sounds like a bug. I think the code generator should not try to string match whatever is inside `{=...=}` to look for a `*`.

It's not a bug, it's intentional. It's how we determine whether or not to do reference counting. We can probably come up with better ways of doing this, however.

**Comment by lhstrh** [comment]
> Interesting... Maybe C should support a type syntax like `token<foo>`? Since C doesn't support generics, this doesn't conflict with C syntax itself

Interesting proposal!

**Comment by Soroosh129** [comment]
> It's not a bug, it's intentional. It's how we determine whether or not to do reference counting.

If I understand correctly, a type with a trailing `*` will be a token type. So `state foo:bar*` is a token type. But why is `state foo:{=bar*=}` also a token type?

**Comment by edwardalee** [comment]
I think it is because at the time the code was first written, our syntax did not allow `input foo:bar*` (note that tokens are not used for state variables, only for inputs and outputs).

**Comment by Soroosh129** [comment]
I see. That makes sense. 

I also like @oowekyala's suggestion of introducing a `token<foo>` type. It is a similar syntax to something like `std::shared_ptr<foo>`, which is also created, at least partly, to help with reference counting.

**Comment by edwardalee** [comment]
Yes, I agree that this is a good idea.

**Comment by cmnrd** [comment]
Is this issue addressed by #620?

**Comment by lhstrh** [comment]
I'm not sure whether `{= 0 =}` is still an issue, but the suggestion to make token types explicit is a good one and should be implemented. Should we just rename this issue to `Implement token type for C target`? @cmnrd and @oowekyala, please advise.

**Comment by cmnrd** [comment]
I think there are two issues at place here. The first is that we sometimes interpret contents of `{=...=}` which we shouldn't do. This is what this issue is about. Then there is the discussion of how token types are handled in the C target. This is completely orthogonal and should have its own issue or discussion.

**Comment by oowekyala** [comment]
I created #1479 to track the C type thing separately. This issue remains about `{=0=}` as a time literal, also see https://github.com/lf-lang/lingua-franca/issues/810#issuecomment-998554028 for more justification
